# Generated by Django 2.1.5 on 2020-06-07 06:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('lectures_conducted', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('div', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('lectures_attended', models.IntegerField(default=0, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Section_class')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='section_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Section_class'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_teach', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Lecture'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='students_present',
            field=models.ManyToManyField(to='app1.Students'),
        ),
    ]
