# Generated by Django 2.1.5 on 2020-07-24 05:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200724_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section_class',
            name='co_owner',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
