# Generated by Django 2.1.5 on 2020-07-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20200701_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='questions'),
        ),
        migrations.AlterField(
            model_name='question',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='question'),
        ),
    ]
