# Generated by Django 2.1.5 on 2020-07-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20200703_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='name2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
