# Generated by Django 2.1.5 on 2020-07-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_quiz_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='roll_out_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='stop_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
