# Generated by Django 2.1.5 on 2020-07-06 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_auto_20200706_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='roll_out_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='stop_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
