# Generated by Django 2.1.5 on 2020-07-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_remove_quiz_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiztaker',
            name='date_finished',
        ),
        migrations.RemoveField(
            model_name='quiztaker',
            name='timestamp',
        ),
    ]
