# Generated by Django 2.1.5 on 2020-07-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_auto_20200713_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='img',
        ),
    ]
