# Generated by Django 2.1.5 on 2020-07-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_remove_question_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
