# Generated by Django 2.1.5 on 2020-07-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20200630_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.ImageField(blank=True, upload_to='question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='label',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.CharField(max_length=5000),
        ),
    ]
