# Generated by Django 2.1.5 on 2020-07-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_auto_20200706_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='name2',
        ),
    ]
