# Generated by Django 2.1.5 on 2020-07-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_auto_20200706_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='img',
            new_name='img1',
        ),
        migrations.AlterField(
            model_name='answer',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='answers'),
        ),
    ]
