# Generated by Django 2.1.5 on 2020-08-09 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
    ]
